
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epvusqqvjqrnrqgoyusu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwdnVzcXF2anFybnJxZ295dXN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMjQyNDUsImV4cCI6MjA2NTgwMDI0NX0.sXTofLLJCl26TW0gYcvHT0bCvemQ_67VKQKdC5LAu1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
